"use client";

import { useCallback, useEffect, useState } from "react";
import {
  ErrorPanel,
  InlineNotice,
  LoadingPanel,
  PageHeader,
  PortalCard,
  Toast,
} from "@/app/components/citizen/PortalUi";
import { fetchCitizen } from "@/app/lib/fetchCitizen";
import type { ApiEnvelope } from "@/app/lib/citizen/types";

type DeveloperResources = {
  api_key: string | null;
  swagger_url: string;
  base_url: string;
  endpoints: Array<{ method: string; path: string; name: string; description: string }>;
};

const methodTone: Record<string, string> = {
  GET: "#1769e0",
  POST: "#138b69",
  PUT: "#7652d9",
  DELETE: "#d94c59",
};

export default function DeveloperResourcesPage() {
  const [resources, setResources] = useState<DeveloperResources | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [toast, setToast] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const response = await fetchCitizen<ApiEnvelope<DeveloperResources>>(
        "customer/developer-resources",
      );
      setResources(response.data);
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "Developer resources are unavailable.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  const copy = async (value: string, label: string) => {
    await navigator.clipboard.writeText(value);
    setToast(`${label} copied.`);
  };

  if (loading) return <LoadingPanel label="Loading protected API resources…" />;
  if (error || !resources) return <ErrorPanel message={error || "No API resources were returned."} retry={() => void load()} />;

  const example = `const response = await fetch('${resources.base_url}/customer/websites', {\n  headers: {\n    Authorization: 'Bearer <secure-session-token>',\n    Accept: 'application/json'\n  }\n});\n\nconst { data } = await response.json();`;

  return (
    <div className="page-enter">
      <PageHeader
        eyebrow="API integration center"
        title="Developer resources"
        description="Use the real NestJS endpoint catalog, your account-bound key, and generated OpenAPI documentation to integrate Accessimate workflows safely."
        actions={<a className="citizen-button primary" href={resources.swagger_url} target="_blank" rel="noreferrer"><i className="fa-solid fa-book-open" /> Open Swagger API <i className="fa-solid fa-arrow-up-right-from-square" /></a>}
      />

      <div className="portal-grid two">
        <PortalCard>
          <div className="portal-card-head"><div><h2>API base URL</h2><p>Current deployed backend origin.</p></div><span className="portal-status positive"><span />Online</span></div>
          <div className="portal-card-body"><div className="code-block"><button type="button" onClick={() => void copy(resources.base_url, "Base URL")}>Copy</button>{resources.base_url}</div></div>
        </PortalCard>
        <PortalCard>
          <div className="portal-card-head"><div><h2>Account API key</h2><p>Used by account-bound browser integrations.</p></div><i className="fa-solid fa-key" style={{ color: "#d88b20" }} /></div>
          <div className="portal-card-body"><div className="code-block"><button type="button" onClick={() => void copy(resources.api_key || "", "API key")}>Copy</button>{resources.api_key || "Not provisioned"}</div></div>
        </PortalCard>
      </div>

      <div style={{ marginTop: 17 }}><InlineNotice tone="warning"><strong>Security model:</strong>&nbsp; browser requests go through the same-site Next.js BFF and an HttpOnly session cookie. Raw bearer tokens are never exposed to frontend JavaScript in this deployment.</InlineNotice></div>

      <PortalCard style={{ marginTop: 17 }}>
        <div className="portal-card-head"><div><h2>Citizen API catalog</h2><p>Generated by the running backend service—not hard-coded proposal content.</p></div><span style={{ color: "var(--citizen-muted)", fontSize: 10 }}>{resources.endpoints.length} endpoints</span></div>
        <div className="portal-card-body" style={{ display: "grid", gap: 10 }}>
          {resources.endpoints.map((endpoint) => (
            <article key={`${endpoint.method}-${endpoint.path}`} style={{ display: "grid", gridTemplateColumns: "70px minmax(180px,.7fr) minmax(240px,1.3fr) 34px", alignItems: "center", gap: 12, padding: 12, border: "1px solid var(--citizen-border)", borderRadius: 11 }}>
              <strong style={{ color: methodTone[endpoint.method] || "var(--citizen-muted)", fontSize: 10 }}>{endpoint.method}</strong>
              <div className="table-primary"><strong>{endpoint.name}</strong><small style={{ fontFamily: "var(--font-geist-mono)" }}>{endpoint.path}</small></div>
              <p style={{ margin: 0, color: "var(--citizen-muted)", fontSize: 10, lineHeight: 1.5 }}>{endpoint.description}</p>
              <button className="citizen-icon-button" type="button" onClick={() => void copy(`${resources.base_url}${endpoint.path}`, endpoint.name)} aria-label={`Copy ${endpoint.name} URL`}><i className="fa-regular fa-copy" /></button>
            </article>
          ))}
        </div>
      </PortalCard>

      <PortalCard style={{ marginTop: 17 }}>
        <div className="portal-card-head"><div><h2>Authenticated request pattern</h2><p>Server-side integration example; replace the placeholder with a securely stored token.</p></div></div>
        <div className="portal-card-body"><div className="code-block"><button type="button" onClick={() => void copy(example, "Request example")}>Copy</button>{example}</div></div>
      </PortalCard>
      {toast && <Toast message={toast} onClose={() => setToast(null)} />}
    </div>
  );
}
